/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AccountRouteImport } from './routes/account'
import { Route as AdminRouteRouteImport } from './routes/admin/route'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as LoginRouteImport } from './routes/login'
import { Route as MerchantRouteRouteImport } from './routes/merchant/route'
import { Route as ReportRouteImport } from './routes/report'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as SetupRouteImport } from './routes/setup'
import { Route as TrackRouteImport } from './routes/track'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AdminFinanceRouteImport } from './routes/admin/finance'
import { Route as AdminStaffRouteImport } from './routes/admin/staff'
import { Route as AdminWebsiteRouteImport } from './routes/admin/website'
import { Route as MerchantIndexRouteImport } from './routes/merchant/index'
import { Route as MerchantDeliveriesRouteImport } from './routes/merchant/deliveries'
import { Route as MerchantHistoryRouteImport } from './routes/merchant/history'
import { Route as MerchantLoginRouteImport } from './routes/merchant_.login'
import { Route as PayCallbackRouteImport } from './routes/pay.callback'
import { Route as PrintIdRouteImport } from './routes/print.$id'
import { Route as StaffLoginRouteImport } from './routes/staff.login'
import { Route as StatementIdRouteImport } from './routes/statement.$id'
import { Route as AdminMerchantsIndexRouteImport } from './routes/admin/merchants/index'
import { Route as AdminMerchantsIdRouteImport } from './routes/admin/merchants/$id'
import { Route as AdminShipmentsIndexRouteImport } from './routes/admin/shipments/index'
import { Route as AdminShipmentsIdRouteImport } from './routes/admin/shipments/$id'
import { Route as AdminShipmentsNewRouteImport } from './routes/admin/shipments/new'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const MerchantRouteRoute = MerchantRouteRouteImport.update({
  id: '/merchant',
  path: '/merchant',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportRoute = ReportRouteImport.update({
  id: '/report',
  path: '/report',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const SetupRoute = SetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const TrackRoute = TrackRouteImport.update({
  id: '/track',
  path: '/track',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminFinanceRoute = AdminFinanceRouteImport.update({
  id: '/finance',
  path: '/finance',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminStaffRoute = AdminStaffRouteImport.update({
  id: '/staff',
  path: '/staff',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminWebsiteRoute = AdminWebsiteRouteImport.update({
  id: '/website',
  path: '/website',
  getParentRoute: () => AdminRouteRoute,
} as any)
const MerchantIndexRoute = MerchantIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MerchantRouteRoute,
} as any)
const MerchantDeliveriesRoute = MerchantDeliveriesRouteImport.update({
  id: '/deliveries',
  path: '/deliveries',
  getParentRoute: () => MerchantRouteRoute,
} as any)
const MerchantHistoryRoute = MerchantHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => MerchantRouteRoute,
} as any)
const MerchantLoginRoute = MerchantLoginRouteImport.update({
  id: '/merchant_/login',
  path: '/merchant/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PayCallbackRoute = PayCallbackRouteImport.update({
  id: '/pay/callback',
  path: '/pay/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const PrintIdRoute = PrintIdRouteImport.update({
  id: '/print/$id',
  path: '/print/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffLoginRoute = StaffLoginRouteImport.update({
  id: '/staff/login',
  path: '/staff/login',
  getParentRoute: () => rootRouteImport,
} as any)
const StatementIdRoute = StatementIdRouteImport.update({
  id: '/statement/$id',
  path: '/statement/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminMerchantsIndexRoute = AdminMerchantsIndexRouteImport.update({
  id: '/merchants/',
  path: '/merchants/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminMerchantsIdRoute = AdminMerchantsIdRouteImport.update({
  id: '/merchants/$id',
  path: '/merchants/$id',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminShipmentsIndexRoute = AdminShipmentsIndexRouteImport.update({
  id: '/shipments/',
  path: '/shipments/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminShipmentsIdRoute = AdminShipmentsIdRouteImport.update({
  id: '/shipments/$id',
  path: '/shipments/$id',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminShipmentsNewRoute = AdminShipmentsNewRouteImport.update({
  id: '/shipments/new',
  path: '/shipments/new',
  getParentRoute: () => AdminRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/merchant': typeof MerchantRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/account': typeof AccountRoute
  '/contact': typeof ContactRoute
  '/login': typeof LoginRoute
  '/report': typeof ReportRoute
  '/services': typeof ServicesRoute
  '/setup': typeof SetupRoute
  '/track': typeof TrackRoute
  '/admin/finance': typeof AdminFinanceRoute
  '/admin/staff': typeof AdminStaffRoute
  '/admin/website': typeof AdminWebsiteRoute
  '/merchant/deliveries': typeof MerchantDeliveriesRoute
  '/merchant/history': typeof MerchantHistoryRoute
  '/merchant/login': typeof MerchantLoginRoute
  '/pay/callback': typeof PayCallbackRoute
  '/print/$id': typeof PrintIdRoute
  '/staff/login': typeof StaffLoginRoute
  '/statement/$id': typeof StatementIdRoute
  '/admin/': typeof AdminIndexRoute
  '/merchant/': typeof MerchantIndexRoute
  '/admin/merchants/$id': typeof AdminMerchantsIdRoute
  '/admin/shipments/$id': typeof AdminShipmentsIdRoute
  '/admin/shipments/new': typeof AdminShipmentsNewRoute
  '/admin/merchants/': typeof AdminMerchantsIndexRoute
  '/admin/shipments/': typeof AdminShipmentsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/account': typeof AccountRoute
  '/contact': typeof ContactRoute
  '/login': typeof LoginRoute
  '/report': typeof ReportRoute
  '/services': typeof ServicesRoute
  '/setup': typeof SetupRoute
  '/track': typeof TrackRoute
  '/admin/finance': typeof AdminFinanceRoute
  '/admin/staff': typeof AdminStaffRoute
  '/admin/website': typeof AdminWebsiteRoute
  '/merchant/deliveries': typeof MerchantDeliveriesRoute
  '/merchant/history': typeof MerchantHistoryRoute
  '/merchant/login': typeof MerchantLoginRoute
  '/pay/callback': typeof PayCallbackRoute
  '/print/$id': typeof PrintIdRoute
  '/staff/login': typeof StaffLoginRoute
  '/statement/$id': typeof StatementIdRoute
  '/admin': typeof AdminIndexRoute
  '/merchant': typeof MerchantIndexRoute
  '/admin/merchants/$id': typeof AdminMerchantsIdRoute
  '/admin/shipments/$id': typeof AdminShipmentsIdRoute
  '/admin/shipments/new': typeof AdminShipmentsNewRoute
  '/admin/merchants': typeof AdminMerchantsIndexRoute
  '/admin/shipments': typeof AdminShipmentsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/merchant': typeof MerchantRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/account': typeof AccountRoute
  '/contact': typeof ContactRoute
  '/login': typeof LoginRoute
  '/report': typeof ReportRoute
  '/services': typeof ServicesRoute
  '/setup': typeof SetupRoute
  '/track': typeof TrackRoute
  '/admin/finance': typeof AdminFinanceRoute
  '/admin/staff': typeof AdminStaffRoute
  '/admin/website': typeof AdminWebsiteRoute
  '/merchant/deliveries': typeof MerchantDeliveriesRoute
  '/merchant/history': typeof MerchantHistoryRoute
  '/merchant_/login': typeof MerchantLoginRoute
  '/pay/callback': typeof PayCallbackRoute
  '/print/$id': typeof PrintIdRoute
  '/staff/login': typeof StaffLoginRoute
  '/statement/$id': typeof StatementIdRoute
  '/admin/': typeof AdminIndexRoute
  '/merchant/': typeof MerchantIndexRoute
  '/admin/merchants/$id': typeof AdminMerchantsIdRoute
  '/admin/shipments/$id': typeof AdminShipmentsIdRoute
  '/admin/shipments/new': typeof AdminShipmentsNewRoute
  '/admin/merchants/': typeof AdminMerchantsIndexRoute
  '/admin/shipments/': typeof AdminShipmentsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/merchant'
    | '/about'
    | '/account'
    | '/contact'
    | '/login'
    | '/report'
    | '/services'
    | '/setup'
    | '/track'
    | '/admin/finance'
    | '/admin/staff'
    | '/admin/website'
    | '/merchant/deliveries'
    | '/merchant/history'
    | '/merchant/login'
    | '/pay/callback'
    | '/print/$id'
    | '/staff/login'
    | '/statement/$id'
    | '/admin/'
    | '/merchant/'
    | '/admin/merchants/$id'
    | '/admin/shipments/$id'
    | '/admin/shipments/new'
    | '/admin/merchants/'
    | '/admin/shipments/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/account'
    | '/contact'
    | '/login'
    | '/report'
    | '/services'
    | '/setup'
    | '/track'
    | '/admin/finance'
    | '/admin/staff'
    | '/admin/website'
    | '/merchant/deliveries'
    | '/merchant/history'
    | '/merchant/login'
    | '/pay/callback'
    | '/print/$id'
    | '/staff/login'
    | '/statement/$id'
    | '/admin'
    | '/merchant'
    | '/admin/merchants/$id'
    | '/admin/shipments/$id'
    | '/admin/shipments/new'
    | '/admin/merchants'
    | '/admin/shipments'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/merchant'
    | '/about'
    | '/account'
    | '/contact'
    | '/login'
    | '/report'
    | '/services'
    | '/setup'
    | '/track'
    | '/admin/finance'
    | '/admin/staff'
    | '/admin/website'
    | '/merchant/deliveries'
    | '/merchant/history'
    | '/merchant_/login'
    | '/pay/callback'
    | '/print/$id'
    | '/staff/login'
    | '/statement/$id'
    | '/admin/'
    | '/merchant/'
    | '/admin/merchants/$id'
    | '/admin/shipments/$id'
    | '/admin/shipments/new'
    | '/admin/merchants/'
    | '/admin/shipments/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  MerchantRouteRoute: typeof MerchantRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  AccountRoute: typeof AccountRoute
  ContactRoute: typeof ContactRoute
  LoginRoute: typeof LoginRoute
  ReportRoute: typeof ReportRoute
  ServicesRoute: typeof ServicesRoute
  SetupRoute: typeof SetupRoute
  TrackRoute: typeof TrackRoute
  MerchantLoginRoute: typeof MerchantLoginRoute
  PayCallbackRoute: typeof PayCallbackRoute
  PrintIdRoute: typeof PrintIdRoute
  StaffLoginRoute: typeof StaffLoginRoute
  StatementIdRoute: typeof StatementIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/merchant': {
      id: '/merchant'
      path: '/merchant'
      fullPath: '/merchant'
      preLoaderRoute: typeof MerchantRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/report': {
      id: '/report'
      path: '/report'
      fullPath: '/report'
      preLoaderRoute: typeof ReportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/setup': {
      id: '/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof SetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/track': {
      id: '/track'
      path: '/track'
      fullPath: '/track'
      preLoaderRoute: typeof TrackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/finance': {
      id: '/admin/finance'
      path: '/finance'
      fullPath: '/admin/finance'
      preLoaderRoute: typeof AdminFinanceRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/staff': {
      id: '/admin/staff'
      path: '/staff'
      fullPath: '/admin/staff'
      preLoaderRoute: typeof AdminStaffRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/website': {
      id: '/admin/website'
      path: '/website'
      fullPath: '/admin/website'
      preLoaderRoute: typeof AdminWebsiteRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/merchant/': {
      id: '/merchant/'
      path: '/'
      fullPath: '/merchant/'
      preLoaderRoute: typeof MerchantIndexRouteImport
      parentRoute: typeof MerchantRouteRoute
    }
    '/merchant/deliveries': {
      id: '/merchant/deliveries'
      path: '/deliveries'
      fullPath: '/merchant/deliveries'
      preLoaderRoute: typeof MerchantDeliveriesRouteImport
      parentRoute: typeof MerchantRouteRoute
    }
    '/merchant/history': {
      id: '/merchant/history'
      path: '/history'
      fullPath: '/merchant/history'
      preLoaderRoute: typeof MerchantHistoryRouteImport
      parentRoute: typeof MerchantRouteRoute
    }
    '/merchant_/login': {
      id: '/merchant_/login'
      path: '/merchant/login'
      fullPath: '/merchant/login'
      preLoaderRoute: typeof MerchantLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pay/callback': {
      id: '/pay/callback'
      path: '/pay/callback'
      fullPath: '/pay/callback'
      preLoaderRoute: typeof PayCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/print/$id': {
      id: '/print/$id'
      path: '/print/$id'
      fullPath: '/print/$id'
      preLoaderRoute: typeof PrintIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff/login': {
      id: '/staff/login'
      path: '/staff/login'
      fullPath: '/staff/login'
      preLoaderRoute: typeof StaffLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/statement/$id': {
      id: '/statement/$id'
      path: '/statement/$id'
      fullPath: '/statement/$id'
      preLoaderRoute: typeof StatementIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/merchants/': {
      id: '/admin/merchants/'
      path: '/merchants'
      fullPath: '/admin/merchants/'
      preLoaderRoute: typeof AdminMerchantsIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/merchants/$id': {
      id: '/admin/merchants/$id'
      path: '/merchants/$id'
      fullPath: '/admin/merchants/$id'
      preLoaderRoute: typeof AdminMerchantsIdRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/shipments/': {
      id: '/admin/shipments/'
      path: '/shipments'
      fullPath: '/admin/shipments/'
      preLoaderRoute: typeof AdminShipmentsIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/shipments/$id': {
      id: '/admin/shipments/$id'
      path: '/shipments/$id'
      fullPath: '/admin/shipments/$id'
      preLoaderRoute: typeof AdminShipmentsIdRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/shipments/new': {
      id: '/admin/shipments/new'
      path: '/shipments/new'
      fullPath: '/admin/shipments/new'
      preLoaderRoute: typeof AdminShipmentsNewRouteImport
      parentRoute: typeof AdminRouteRoute
    }
  }
}

interface AdminRouteRouteChildren {
  AdminFinanceRoute: typeof AdminFinanceRoute
  AdminStaffRoute: typeof AdminStaffRoute
  AdminWebsiteRoute: typeof AdminWebsiteRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminMerchantsIdRoute: typeof AdminMerchantsIdRoute
  AdminShipmentsIdRoute: typeof AdminShipmentsIdRoute
  AdminShipmentsNewRoute: typeof AdminShipmentsNewRoute
  AdminMerchantsIndexRoute: typeof AdminMerchantsIndexRoute
  AdminShipmentsIndexRoute: typeof AdminShipmentsIndexRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminFinanceRoute: AdminFinanceRoute,
  AdminStaffRoute: AdminStaffRoute,
  AdminWebsiteRoute: AdminWebsiteRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminMerchantsIdRoute: AdminMerchantsIdRoute,
  AdminShipmentsIdRoute: AdminShipmentsIdRoute,
  AdminShipmentsNewRoute: AdminShipmentsNewRoute,
  AdminMerchantsIndexRoute: AdminMerchantsIndexRoute,
  AdminShipmentsIndexRoute: AdminShipmentsIndexRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

interface MerchantRouteRouteChildren {
  MerchantDeliveriesRoute: typeof MerchantDeliveriesRoute
  MerchantHistoryRoute: typeof MerchantHistoryRoute
  MerchantIndexRoute: typeof MerchantIndexRoute
}

const MerchantRouteRouteChildren: MerchantRouteRouteChildren = {
  MerchantDeliveriesRoute: MerchantDeliveriesRoute,
  MerchantHistoryRoute: MerchantHistoryRoute,
  MerchantIndexRoute: MerchantIndexRoute,
}

const MerchantRouteRouteWithChildren = MerchantRouteRoute._addFileChildren(
  MerchantRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRouteRoute: AdminRouteRouteWithChildren,
  MerchantRouteRoute: MerchantRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  AccountRoute: AccountRoute,
  ContactRoute: ContactRoute,
  LoginRoute: LoginRoute,
  ReportRoute: ReportRoute,
  ServicesRoute: ServicesRoute,
  SetupRoute: SetupRoute,
  TrackRoute: TrackRoute,
  MerchantLoginRoute: MerchantLoginRoute,
  PayCallbackRoute: PayCallbackRoute,
  PrintIdRoute: PrintIdRoute,
  StaffLoginRoute: StaffLoginRoute,
  StatementIdRoute: StatementIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
