/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteRouteImport } from './routes/admin/route'
import { Route as LoginRouteImport } from './routes/login'
import { Route as SetupRouteImport } from './routes/setup'
import { Route as TrackRouteImport } from './routes/track'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AdminStaffRouteImport } from './routes/admin/staff'
import { Route as PrintIdRouteImport } from './routes/print.$id'
import { Route as AdminShipmentsIndexRouteImport } from './routes/admin/shipments/index'
import { Route as AdminShipmentsIdRouteImport } from './routes/admin/shipments/$id'
import { Route as AdminShipmentsNewRouteImport } from './routes/admin/shipments/new'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const SetupRoute = SetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const TrackRoute = TrackRouteImport.update({
  id: '/track',
  path: '/track',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminStaffRoute = AdminStaffRouteImport.update({
  id: '/staff',
  path: '/staff',
  getParentRoute: () => AdminRouteRoute,
} as any)
const PrintIdRoute = PrintIdRouteImport.update({
  id: '/print/$id',
  path: '/print/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminShipmentsIndexRoute = AdminShipmentsIndexRouteImport.update({
  id: '/shipments/',
  path: '/shipments/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminShipmentsIdRoute = AdminShipmentsIdRouteImport.update({
  id: '/shipments/$id',
  path: '/shipments/$id',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminShipmentsNewRoute = AdminShipmentsNewRouteImport.update({
  id: '/shipments/new',
  path: '/shipments/new',
  getParentRoute: () => AdminRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/setup': typeof SetupRoute
  '/track': typeof TrackRoute
  '/admin/staff': typeof AdminStaffRoute
  '/print/$id': typeof PrintIdRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/shipments/$id': typeof AdminShipmentsIdRoute
  '/admin/shipments/new': typeof AdminShipmentsNewRoute
  '/admin/shipments/': typeof AdminShipmentsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/setup': typeof SetupRoute
  '/track': typeof TrackRoute
  '/admin/staff': typeof AdminStaffRoute
  '/print/$id': typeof PrintIdRoute
  '/admin': typeof AdminIndexRoute
  '/admin/shipments/$id': typeof AdminShipmentsIdRoute
  '/admin/shipments/new': typeof AdminShipmentsNewRoute
  '/admin/shipments': typeof AdminShipmentsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/setup': typeof SetupRoute
  '/track': typeof TrackRoute
  '/admin/staff': typeof AdminStaffRoute
  '/print/$id': typeof PrintIdRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/shipments/$id': typeof AdminShipmentsIdRoute
  '/admin/shipments/new': typeof AdminShipmentsNewRoute
  '/admin/shipments/': typeof AdminShipmentsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/login'
    | '/setup'
    | '/track'
    | '/admin/staff'
    | '/print/$id'
    | '/admin/'
    | '/admin/shipments/$id'
    | '/admin/shipments/new'
    | '/admin/shipments/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/setup'
    | '/track'
    | '/admin/staff'
    | '/print/$id'
    | '/admin'
    | '/admin/shipments/$id'
    | '/admin/shipments/new'
    | '/admin/shipments'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/login'
    | '/setup'
    | '/track'
    | '/admin/staff'
    | '/print/$id'
    | '/admin/'
    | '/admin/shipments/$id'
    | '/admin/shipments/new'
    | '/admin/shipments/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  LoginRoute: typeof LoginRoute
  SetupRoute: typeof SetupRoute
  TrackRoute: typeof TrackRoute
  PrintIdRoute: typeof PrintIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/setup': {
      id: '/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof SetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/track': {
      id: '/track'
      path: '/track'
      fullPath: '/track'
      preLoaderRoute: typeof TrackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/staff': {
      id: '/admin/staff'
      path: '/staff'
      fullPath: '/admin/staff'
      preLoaderRoute: typeof AdminStaffRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/print/$id': {
      id: '/print/$id'
      path: '/print/$id'
      fullPath: '/print/$id'
      preLoaderRoute: typeof PrintIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/shipments/': {
      id: '/admin/shipments/'
      path: '/shipments'
      fullPath: '/admin/shipments/'
      preLoaderRoute: typeof AdminShipmentsIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/shipments/$id': {
      id: '/admin/shipments/$id'
      path: '/shipments/$id'
      fullPath: '/admin/shipments/$id'
      preLoaderRoute: typeof AdminShipmentsIdRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/shipments/new': {
      id: '/admin/shipments/new'
      path: '/shipments/new'
      fullPath: '/admin/shipments/new'
      preLoaderRoute: typeof AdminShipmentsNewRouteImport
      parentRoute: typeof AdminRouteRoute
    }
  }
}

interface AdminRouteRouteChildren {
  AdminStaffRoute: typeof AdminStaffRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminShipmentsIdRoute: typeof AdminShipmentsIdRoute
  AdminShipmentsNewRoute: typeof AdminShipmentsNewRoute
  AdminShipmentsIndexRoute: typeof AdminShipmentsIndexRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminStaffRoute: AdminStaffRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminShipmentsIdRoute: AdminShipmentsIdRoute,
  AdminShipmentsNewRoute: AdminShipmentsNewRoute,
  AdminShipmentsIndexRoute: AdminShipmentsIndexRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRouteRoute: AdminRouteRouteWithChildren,
  LoginRoute: LoginRoute,
  SetupRoute: SetupRoute,
  TrackRoute: TrackRoute,
  PrintIdRoute: PrintIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
